"""
Report generation module.
Produces a daily HTML report with buy signals and recent performance.
"""

import pandas as pd
from pathlib import Path
from datetime import datetime

REPORTS_DIR = Path(__file__).resolve().parents[2] / "results" / "reports"


def generate_report(signals_df, features_df, report_date):
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    date_str    = pd.Timestamp(report_date).strftime("%Y-%m-%d")
    report_path = REPORTS_DIR / f"report_{date_str}.html"

    recent = (
        features_df[features_df["Date"] == report_date]
        [["Ticker", "Close", "return_5d", "return_20d", "rsi_14", "volatility_20d"]]
        .copy()
    )

    if signals_df.empty:
        signal_rows = "<tr><td colspan='6' style='text-align:center;color:#888'>No signals today</td></tr>"
    else:
        signal_rows = ""
        for _, row in signals_df.iterrows():
            prob_pct = f"{row['proba']*100:.1f}%"
            rsi      = f"{row['rsi_14']:.1f}"
            ret5d    = f"{row['return_5d']*100:.2f}%"
            close    = f"${row['Close']:.2f}"
            color    = "#e8f5e9" if row["proba"] >= 0.65 else "#fff8e1"
            strength = "Strong" if row["proba"] >= 0.65 else "Moderate"
            signal_rows += (
                f"<tr style='background:{color}'>"
                f"<td><strong>{row['Ticker']}</strong></td>"
                f"<td>{close}</td><td>{prob_pct}</td>"
                f"<td>{rsi}</td><td>{ret5d}</td>"
                f"<td>{strength}</td></tr>"
            )

    market_rows = ""
    for _, row in recent.sort_values("return_5d", ascending=False).iterrows():
        r5  = row["return_5d"] * 100
        r20 = row["return_20d"] * 100
        r5c  = "#2e7d32" if r5  > 0 else "#c62828"
        r20c = "#2e7d32" if r20 > 0 else "#c62828"
        market_rows += (
            f"<tr><td><strong>{row['Ticker']}</strong></td>"
            f"<td>${row['Close']:.2f}</td>"
            f"<td style='color:{r5c}'>{r5:+.2f}%</td>"
            f"<td style='color:{r20c}'>{r20:+.2f}%</td>"
            f"<td>{row['rsi_14']:.1f}</td></tr>"
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Stock Signal Report -- {date_str}</title>
<style>
  body {{ font-family: -apple-system, sans-serif; background:#f5f7fa; color:#1a1a2e; padding:2rem; }}
  .container {{ max-width:960px; margin:0 auto; }}
  header {{ background:linear-gradient(135deg,#1a1a2e,#16213e); color:white; padding:2rem; border-radius:12px; margin-bottom:2rem; }}
  header h1 {{ font-size:1.8rem; margin-bottom:0.4rem; }}
  header p  {{ opacity:0.7; font-size:0.95rem; }}
  .card {{ background:white; border-radius:12px; padding:1.5rem; margin-bottom:1.5rem; box-shadow:0 2px 8px rgba(0,0,0,0.06); }}
  .card h2 {{ font-size:1.1rem; margin-bottom:1rem; padding-bottom:0.5rem; border-bottom:2px solid #f0f0f0; }}
  table {{ width:100%; border-collapse:collapse; font-size:0.9rem; }}
  th {{ background:#f8f9fa; padding:0.6rem 0.8rem; text-align:left; font-weight:600; color:#555; border-bottom:2px solid #eee; }}
  td {{ padding:0.6rem 0.8rem; border-bottom:1px solid #f0f0f0; }}
  footer {{ text-align:center; color:#aaa; font-size:0.8rem; margin-top:2rem; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>Stock Signal Pipeline</h1>
    <p>Daily Report -- {date_str} | Model: XGBoost, Walk-forward validated</p>
  </header>
  <div class="card">
    <h2>Today's Buy Signals ({len(signals_df)} stocks)</h2>
    <table>
      <thead><tr><th>Ticker</th><th>Price</th><th>Confidence</th><th>RSI(14)</th><th>5d Return</th><th>Signal</th></tr></thead>
      <tbody>{signal_rows}</tbody>
    </table>
  </div>
  <div class="card">
    <h2>Market Overview -- All Tracked Stocks</h2>
    <table>
      <thead><tr><th>Ticker</th><th>Price</th><th>5d Return</th><th>20d Return</th><th>RSI(14)</th></tr></thead>
      <tbody>{market_rows}</tbody>
    </table>
  </div>
  <div class="card">
    <h2>Model Notes</h2>
    <p style="font-size:0.88rem;color:#555;line-height:1.7">
      Signals are generated by an XGBoost binary classifier trained on technical indicators
      (RSI, MACD, Bollinger Bands, SMAs, OBV) across 15 S&P 500 stocks.
      Predicts whether a stock will rise more than 2% over the next 5 trading days.
      Walk-forward cross-validation prevents data leakage.
      <strong>For educational purposes only. Not financial advice.</strong>
    </p>
  </div>
  <footer>Generated by stock-signal-pipeline -- {datetime.now().strftime("%Y-%m-%d %H:%M UTC")} --
  github.com/valofils/stock-signal-pipeline</footer>
</div>
</body>
</html>"""

    report_path.write_text(html, encoding="utf-8")
    print(f"Report saved to {report_path}")
    return report_path
